[project]
name = "r1-v"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "r1-v",
]

[tool.uv.sources]
r1-v = { workspace = true }
